name: Telegram Notifier

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    types: [ opened, closed ]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Telegram notification on push
        if: github.event_name == 'push'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            **🚀 Push ke Branch `${{ github.ref_name }}`**
            
            **Repo:** `${{ github.repository }}`
            **Pelaku:** `${{ github.actor }}`
            **Commit:** `${{ github.event.head_commit.message }}`
            
            Lihat perubahan: ${{ github.event.compare }}

      - name: Send Telegram notification on PR opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            **📬 Pull Request Baru**
            
            **Repo:** `${{ github.repository }}`
            **Pelaku:** `${{ github.actor }}`
            **Judul:** `${{ github.event.pull_request.title }}`
            **Dari:** `${{ github.event.pull_request.head.ref }}`
            **Ke:** `${{ github.event.pull_request.base.ref }}`
            
            Lihat PR: ${{ github.event.pull_request.html_url }}
      
      - name: Send Telegram notification on PR closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            **✅ Pull Request Ditutup**
            
            **Repo:** `${{ github.repository }}`
            **Pelaku:** `${{ github.actor }}`
            **Judul:** `${{ github.event.pull_request.title }}`
            **Status:** ${{ github.event.pull_request.merged && 'Digabung (Merged)' || 'Ditolak (Closed)' }}
            
            Lihat PR: ${{ github.event.pull_request.html_url }}